# Fine-tuning specific configuration
#   author: px
#   date: 2021-03-09
#   version: 1.0

inherit_from: "configs/base_config.yaml"

model:
  arch: "resnet3d50"
  pretrained_path: "path/to/moco_checkpoint.ckpt"
  freeze_backbone: true
  feature_dim: 512
  dropout_rate: 0.5

data:
  n_folds: 5
  test_size: 0.2
  validation_size: 0.15

augmentation:
  rotation_range: 10
  flip_prob: 0.5
  scale_range: [0.95, 1.05]
  translate_range: [-0.05, 0.05]
  noise_std: 0.01
  gamma_range: [0.9, 1.1]
  p_augment: 0.3

training:
  batch_size: 16
  learning_rate: 0.001
  momentum: 0.9
  weight_decay: 0.0001
  max_epochs: 100
  early_stopping_patience: 10

optimizer:
  type: "adam"
  learning_rate: 0.001
  weight_decay: 0.0001

scheduler:
  type: "reduce_on_plateau"
  patience: 5
  factor: 0.5
  min_lr: 1e-6